
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

City.destroy_all
Picture.destroy_all

City.create(name: 'Amsterdam', flag: '🇳🇱')
City.create(name: 'Seoul', flag: '🇰🇷')
City.create(name: 'HongKong', flag: '🇭🇰')
City.create(name: 'Tokyo', flag: '🇯🇵')
City.create(name: 'Lisbon', flag: '🇵🇹')
City.create(name: 'Berlin', flag: '🇩🇪')
City.create(name: 'Miami', flag: '🇺🇸')
City.create(name: 'Milan', flag: '🇮🇹')
City.create(name: 'London', flag: '🇬🇧')
City.create(name: 'Copenhagen', flag: '🇩🇰')
City.create(name: 'Macao', flag: '🇲🇴')
City.create(name: 'Krakow', flag: '🇵🇱')
City.create(name: 'Chania', flag: '🇬🇷')
City.create(name: 'Bangkok', flag: '🇹🇭')
City.create(name: 'Bali', flag: '🇮🇩')
City.create(name: 'Sydney', flag: '🇦🇺')
City.create(name: 'Zagreb', flag: '🇭🇷')
City.create(name: 'Paris', flag: '🇫🇷')
City.create(name: 'Taipei', flag: '🇹🇼')
City.create(name: 'TelAviv', flag: '🇮🇱')

Picture.create(url: 'amsterdam/amsterdam0.jpg', city_id: 1)
Picture.create(url: 'amsterdam/amsterdam1.jpg', city_id: 1)
Picture.create(url: 'amsterdam/amsterdam2.jpg', city_id: 1)
Picture.create(url: 'amsterdam/amsterdam3.jpg', city_id: 1)
Picture.create(url: 'amsterdam/amsterdam4.jpg', city_id: 1)
Picture.create(url: 'amsterdam/amsterdam5.jpg', city_id: 1)
Picture.create(url: 'amsterdam/amsterdam6.jpg', city_id: 1)
Picture.create(url: 'amsterdam/amsterdam7.jpg', city_id: 1)
Picture.create(url: 'amsterdam/amsterdam8.jpg', city_id: 1)

Picture.create(url: 'seoul/seoul0.jpg', city_id: 2)
Picture.create(url: 'seoul/seoul1.jpg', city_id: 2)
Picture.create(url: 'seoul/seoul2.jpg', city_id: 2)
Picture.create(url: 'seoul/seoul3.jpg', city_id: 2)
Picture.create(url: 'seoul/seoul4.jpg', city_id: 2)
Picture.create(url: 'seoul/seoul5.jpg', city_id: 2)

Picture.create(url: 'hongkong/hongkong0.jpg', city_id: 3)
Picture.create(url: 'hongkong/hongkong1.m4v', city_id: 3)
Picture.create(url: 'hongkong/hongkong2.jpg', city_id: 3)
Picture.create(url: 'hongkong/hongkong3.jpg', city_id: 3)
Picture.create(url: 'hongkong/hongkong4.jpg', city_id: 3)
Picture.create(url: 'hongkong/hongkong5.jpg', city_id: 3)
Picture.create(url: 'hongkong/hongkong6.jpg', city_id: 3)
Picture.create(url: 'hongkong/hongkong7.jpg', city_id: 3)
Picture.create(url: 'hongkong/hongkong8.jpg', city_id: 3)
Picture.create(url: 'hongkong/hongkong9.jpg', city_id: 3)

Picture.create(url: 'tokyo/tokyo0.jpg', city_id: 4)
Picture.create(url: 'tokyo/tokyo1.jpg', city_id: 4)

Picture.create(url: 'lisbon/lisbon0.jpg', city_id: 5)
Picture.create(url: 'lisbon/lisbon1.jpg', city_id: 5)
Picture.create(url: 'lisbon/lisbon2.jpg', city_id: 5)
Picture.create(url: 'lisbon/lisbon3.jpg', city_id: 5)
Picture.create(url: 'lisbon/lisbon4.jpg', city_id: 5)
Picture.create(url: 'lisbon/lisbon5.jpg', city_id: 5)
Picture.create(url: 'lisbon/lisbon6.jpg', city_id: 5)
Picture.create(url: 'lisbon/lisbon7.jpg', city_id: 5)
Picture.create(url: 'lisbon/lisbon8.jpg', city_id: 5)

Picture.create(url: 'berlin/berlin0.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin1.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin2.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin3.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin4.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin5.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin6.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin7.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin8.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin9.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin10.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin11.jpg', city_id: 6)
Picture.create(url: 'berlin/berlin12.jpg', city_id: 6)

Picture.create(url: 'miami/miami0.jpg', city_id: 7)
Picture.create(url: 'miami/miami1.jpg', city_id: 7)
Picture.create(url: 'miami/miami2.jpg', city_id: 7)
Picture.create(url: 'miami/miami3.jpg', city_id: 7)
Picture.create(url: 'miami/miami4.jpg', city_id: 7)
Picture.create(url: 'miami/miami5.jpg', city_id: 7)
Picture.create(url: 'miami/miami6.jpg', city_id: 7)

Picture.create(url: 'milan/milan0.jpg', city_id: 8)
Picture.create(url: 'milan/milan1.jpg', city_id: 8)
Picture.create(url: 'milan/milan2.jpg', city_id: 8)
Picture.create(url: 'milan/milan3.jpg', city_id: 8)

Picture.create(url: 'london/london0.jpg', city_id: 9)
Picture.create(url: 'london/london1.jpg', city_id: 9)
Picture.create(url: 'london/london2.jpg', city_id: 9)
Picture.create(url: 'london/london3.jpg', city_id: 9)

Picture.create(url: 'copenhagen/copenhagen0.jpg', city_id: 10)
Picture.create(url: 'copenhagen/copenhagen1.jpg', city_id: 10)
Picture.create(url: 'copenhagen/copenhagen2.jpg', city_id: 10)
Picture.create(url: 'copenhagen/copenhagen3.jpg', city_id: 10)
Picture.create(url: 'copenhagen/copenhagen4.jpg', city_id: 10)

Picture.create(url: 'macao/macau0.jpg', city_id: 11)
Picture.create(url: 'macao/macau1.jpg', city_id: 11)
Picture.create(url: 'macao/macau2.jpg', city_id: 11)
Picture.create(url: 'macao/macau3.jpg', city_id: 11)
Picture.create(url: 'macao/macau4.jpg', city_id: 11)

Picture.create(url: 'krakow/krakow0.jpg', city_id: 12)
Picture.create(url: 'krakow/krakow1.jpg', city_id: 12)

Picture.create(url: 'chania/chania0.jpg', city_id: 13)
Picture.create(url: 'chania/chania1.jpg', city_id: 13)
Picture.create(url: 'chania/chania2.jpg', city_id: 13)
Picture.create(url: 'chania/chania3.jpg', city_id: 13)
Picture.create(url: 'chania/chania4.jpg', city_id: 13)
Picture.create(url: 'chania/chania5.jpg', city_id: 13)
Picture.create(url: 'chania/chania6.jpg', city_id: 13)
Picture.create(url: 'chania/chania7.jpg', city_id: 13)

Picture.create(url: 'bangkok/bangkok0.jpg', city_id: 14)
Picture.create(url: 'bangkok/bangkok1.jpg', city_id: 14)
Picture.create(url: 'bangkok/bangkok2.jpg', city_id: 14)

Picture.create(url: 'bali/bali0.jpg', city_id: 15)
Picture.create(url: 'bali/bali1.jpg', city_id: 15)
Picture.create(url: 'bali/bali2.jpg', city_id: 15)
Picture.create(url: 'bali/bali3.jpg', city_id: 15)
Picture.create(url: 'bali/bali4.jpg', city_id: 15)
Picture.create(url: 'bali/bali5.jpg', city_id: 15)
Picture.create(url: 'bali/bali6.jpg', city_id: 15)
Picture.create(url: 'bali/bali7.jpg', city_id: 15)
Picture.create(url: 'bali/bali8.jpg', city_id: 15)

Picture.create(url: 'sydney/sydney0.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney1.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney2.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney3.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney4.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney5.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney6.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney7.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney8.jpg', city_id: 16)
Picture.create(url: 'sydney/sydney9.jpg', city_id: 16)

Picture.create(url: 'zagreb/zagreb0.jpg', city_id: 17)
Picture.create(url: 'zagreb/zagreb1.jpg', city_id: 17)
Picture.create(url: 'zagreb/zagreb2.jpg', city_id: 17)
Picture.create(url: 'zagreb/zagreb3.jpg', city_id: 17)
Picture.create(url: 'zagreb/zagreb4.jpg', city_id: 17)
Picture.create(url: 'zagreb/zagreb5.jpg', city_id: 17)
Picture.create(url: 'zagreb/zagreb6.jpg', city_id: 17)
Picture.create(url: 'zagreb/zagreb7.jpg', city_id: 17)

Picture.create(url: 'paris/paris0.jpg', city_id: 18)
Picture.create(url: 'paris/paris1.jpg', city_id: 18)
Picture.create(url: 'paris/paris2.jpg', city_id: 18)
Picture.create(url: 'paris/paris3.jpg', city_id: 18)
Picture.create(url: 'paris/paris4.jpg', city_id: 18)

Picture.create(url: 'taipei/taipei0.jpg', city_id: 19)
Picture.create(url: 'taipei/taipei1.jpg', city_id: 19)
Picture.create(url: 'taipei/taipei2.jpg', city_id: 19)
Picture.create(url: 'taipei/taipei3.jpg', city_id: 19)

Picture.create(url: 'telaviv/telaviv0.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv1.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv2.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv3.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv4.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv5.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv6.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv7.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv8.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv9.jpg', city_id: 20)
Picture.create(url: 'telaviv/telaviv10.jpg', city_id: 20)


